// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommandModal: typeof import('./../components/Command/CommandModal.vue')['default']
    CommandModelBody: typeof import('./../components/Command/CommandModelBody.vue')['default']
    NavBar: typeof import('./../components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsBody: typeof import('./../views/settings/components/SettingsBody.vue')['default']
    SettingsHeader: typeof import('./../views/settings/components/SettingsHeader.vue')['default']
    SettingsSidebar: typeof import('./../views/settings/components/SettingsSidebar.vue')['default']
    SwitchTheme: typeof import('./../components/switchTheme/SwitchTheme.vue')['default']
    TheHeader: typeof import('./../components/TheHeader.vue')['default']
  }
}
